### ISSUE TITLE
merge entre gaia_dev y resoluciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/gaia_cliente#1]
Después de finalizar el proceso del issue #3 se ha de proceder a realizar el merge entre resoluciones dentro de gaia_dev.

---

***nota:*** `gaia_dev` absorbe `resoluciones`

---

***objetivos***

- [x] merge de código de resoluciones a gaia_dev
- [x] resolución de conflictos después del merge

***calidad(debe de ser revisado por un miembro diferente al desarrollador que realizo este issue***
- [x] componentes básicos de resoluciones siguen funcionando.

**Comment by BrayanB24** [comment]
Se inicia el proceso de Merge

**Comment by BrayanB24** [comment]
Se debe revisar el archivo de integración contínua .drone.yml , se toma como base que el proyecto venía siendo desarrollado en estado de pruebas por lo que no se deja el paso de prueba de calidad de software con sonnar y se deja la prueba de build del programa de go.

**Comment by BrayanB24** [comment]
Se realiza de manera correcta el merge entre las ramas gaia_dev y resoluciones, se puede continuar con el siguiente merge.
