### ISSUE TITLE
merge entre gaia_dev y cumplidos_cps_pruebas

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/gaia_cliente#2]
Después de finalizar el proceso del issue #1  se ha de proceder a realizar el merge entre cumplidos_cps_pruebas dentro de gaia_dev.

---

***nota:*** `gaia_dev` absorbe `cumplidos_cps_pruebas`

---

***objetivos***

- [ ] merge de código de cumplidos_cps_pruebas a gaia_dev
- [ ] resolución de conflictos después del merge

***calidad(debe de ser revisado por un miembro diferente al desarrollador que realizo este issue***
- [ ] componentes básicos de cumplidos siguen funcionando.

**Comment by BrayanB24** [comment]
Las actividades del issue #1 se completaron de manera satisfactoria, se puede continuar con el inicio de este issue.
