### ISSUE TITLE
merge entre gaia_dev y necesidades.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/gaia_cliente#8]
Después de finalizar el proceso del issue #6  se ha de proceder a realizar el merge entre necesidades dentro de gaia_dev.

---

***nota:*** `gaia_dev` absorbe `necesidades`

---

***objetivos***

- [x] merge de código de necesidades a gaia_dev
- [x] resolución de conflictos después del merge

***calidad(debe de ser revisado por un miembro diferente al desarrollador que realizo este issue***
- [ ] componentes básicos de resoluciones siguen funcionando.

**Comment by BrayanB24** [comment]
Se inicia el proceso de nmerge

**Comment by BrayanB24** [comment]
Se evidencia una incompatibilidad entre las plataformas a las que se le realiza el merge, pues después de realizarlo el módulo de necesidades deja de funcionar completamente, además hay demasiados archivos modificados, se plantea re evaluar si es necesario este merge, de así serlo se debe dedicar un issue para la solución de estos errores.
